name: enochecker_test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-dink
    env:
      ENOCHECKER_TEST_CHECKER_PORT: 5008
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13
    - name: Install enochecker_test
      run: |
        python -m pip install --upgrade pip
        pip install enochecker_test
    - name: build binary
      run: |
        cd service
        ln -s ../meta/docker-compose.override.yml docker-compose.override.yml
        docker compose run --rm --build build
        rm docker-compose.override.yml

    - name: pin service dockerfile
      uses: attacking-lab/actions/pin-images@main
      with:
        dockerfile: service/Dockerfile
        image-archive: checker_archive
    - name: pin checker dockerfile
      uses: attacking-lab/actions/pin-images@main
      with:
        dockerfile: checker/Dockerfile
        image-archive: checker_archive
      
    - name: start service
      run: |
        cd service
        docker compose up --build --force-recreate -d
    - name: start checker
      run: |
        cd checker
        docker compose up --build --force-recreate -d
    - name: obtain Docker host IP
      run: |
        echo "ENOCHECKER_TEST_SERVICE_ADDRESS=$(docker network inspect bambi-notes_service_default | jq -r '.[].IPAM.Config[].Gateway')" | tee -a $GITHUB_ENV
        echo "ENOCHECKER_TEST_CHECKER_ADDRESS=$(docker network inspect bambi-notes_checker_default | jq -r '.[].IPAM.Config[].Gateway')" | tee -a $GITHUB_ENV
    - name: run enochecker_test
      run: |
        enochecker_test
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v1
      with:
        dest: './logs'
    - name: Print logs
      if: failure()
      run: |
        find ./logs -type f -exec echo -e "\n\e[32m{}\e[0m": \; -exec cat {} \;
    - name: Kill docker containers
      if: failure() || success()
      run: |
        (cd service && docker compose down -v)
        (cd checker && docker compose down -v)
